# Lista #4

## Exercício 7

In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

# BernoulliNB

In [3]:
# Instantiate a CountVectorizer object
vect = CountVectorizer(binary=True)

In [4]:
# Fit and transform X_train into x_train_dtm (document-term matrices - dtm)
x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [5]:
# Transform X_test into X_test_dtm
x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())

[[0 1 1 0 0 1]]


In [6]:
# Instantiate a Bernoulli Naive Bayes model
model = BernoulliNB(binarize=None)

In [7]:
# train the model using X_train_dtm
model.fit(x_train_dtm, y_train)

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [8]:
y_pred_class = model.predict(x_test_dtm)

In [9]:
print(y_pred_class)

['not china']


In [10]:
print(model.predict_proba(x_test_dtm))

[[0.19106679 0.80893321]]


# Explicação

O vetor de teste é idêntico ao quarto vetor de treinamento, o qual pertence à classe 'not-china', e portanto, ele é consequentemente classificado como tal.

# MultinomialNB

In [11]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

In [12]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer()

In [13]:
# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [14]:
# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())

[[0 3 1 0 0 1]]


In [15]:
# Instantiate a Multinomial Naive Bayes model.
model = MultinomialNB()

In [16]:
# train the model using X_train_dtm
model.fit(x_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
y_pred_class = model.predict(x_test_dtm)

In [18]:
print(y_pred_class)

['china']


In [19]:
print(model.predict_proba(x_test_dtm))

[[0.68975861 0.31024139]]


# Explicação

O motivo dessa classificação é que as três ocorrências do indicador positivo 'chinese' no vetor de test superam (tem maior peso) do que as ocorrências dos dois indicadores negativos 'japan' e 'tokyo'.